// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDY4cMRfcXwUIhAKACvKldNk5k-6_n-zO4',
    appId: '1:1081372073317:web:f0a689fc1954a0caea158c',
    messagingSenderId: '1081372073317',
    projectId: 'canteen-app-adani',
    authDomain: 'canteen-app-adani.firebaseapp.com',
    storageBucket: 'canteen-app-adani.firebasestorage.app',
    measurementId: 'G-655E0L5F25',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWrklomuJ5LgYk54cRZ-IQHcs9nNxt-I0',
    appId: '1:1081372073317:android:a9de02d9171aa3c7ea158c',
    messagingSenderId: '1081372073317',
    projectId: 'canteen-app-adani',
    storageBucket: 'canteen-app-adani.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAM_fXri9lBk1y3rU6lMFR2cKjJWLKW50c',
    appId: '1:1081372073317:ios:8caeb454c4a4a271ea158c',
    messagingSenderId: '1081372073317',
    projectId: 'canteen-app-adani',
    storageBucket: 'canteen-app-adani.firebasestorage.app',
    iosBundleId: 'com.adani.canteenAdani',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAM_fXri9lBk1y3rU6lMFR2cKjJWLKW50c',
    appId: '1:1081372073317:ios:8caeb454c4a4a271ea158c',
    messagingSenderId: '1081372073317',
    projectId: 'canteen-app-adani',
    storageBucket: 'canteen-app-adani.firebasestorage.app',
    iosBundleId: 'com.adani.canteenAdani',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDY4cMRfcXwUIhAKACvKldNk5k-6_n-zO4',
    appId: '1:1081372073317:web:be6326198c2e200dea158c',
    messagingSenderId: '1081372073317',
    projectId: 'canteen-app-adani',
    authDomain: 'canteen-app-adani.firebaseapp.com',
    storageBucket: 'canteen-app-adani.firebasestorage.app',
    measurementId: 'G-PR402EL7YP',
  );
}
